# -*- coding: utf-8 -*-
#
# Build configuration file

# Note that not all possible configuration values are present in this
# autogenerated file.
#
# All configuration values have a default; values that are commented out
# serve to show the default.
import os
import sys
from datetime import date


# Add any Sphinx extension module names here, as strings.
extensions = ['sphinx.ext.autodoc', 'sphinx.ext.todo', 'sphinx.ext.coverage',
              'sphinx.ext.viewcode', 'sphinx.ext.imgmath']
templates_path = ['_templates']
source_suffix = '.rst'
master_doc = 'index'
trim_footnote_reference_space = True
project = u'Asinine'
author = u'Asinine Media Inc.'
contributor = u'Brant A. P. Watson'
copyright = f'{date.today().strftime("%Y")}, {author}.'
version = '1.0.0'
release = '1'
exclude_patterns = ['_build', '.env', '.env_python2.6', '.env_python2.7',
                    '.env_python3', '.git', 'resources', ]
show_authors = False
pygments_style = 'sphinx'
on_rtd = os.environ.get('READTHEDOCS', None) == 'True'
on_epub = os.environ.get('EPUB_ENV', None) == 'True'

# Only import and set the theme if we're building docs locally
if not on_rtd and not on_epub:
    import sphinx_rtd_theme
    html_theme = 'sphinx_rtd_theme'
    html_theme_path = [sphinx_rtd_theme.get_html_theme_path()]
    html_style = 'css/theme.css'
    html_static_path = ['_static']

html_title = project
html_short_title = "Asinine"
html_favicon = "_static/favicon.ico"
html_static_path = ['_static']
html_use_index = True
html_show_sphinx = False
html_show_copyright = False
htmlhelp_basename = 'asinine_doc'

# -- Options for LaTeX output ---------------------------------------------
latex_elements = {}
latex_documents = [
    (master_doc, 'Asinine.tex', project,
     author, 'book'),
]
